import test from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from '../src/app.js';
import {openDatabase,openConfiguredDatabase} from '../src/db/database.js';
test('required hosted postgres never falls back to ephemeral SQLite',async()=>{const oldUrl=process.env.DATABASE_URL,oldRequire=process.env.REQUIRE_POSTGRES;try{delete process.env.DATABASE_URL;process.env.REQUIRE_POSTGRES='1';await assert.rejects(openConfiguredDatabase(),/required/);}finally{if(oldUrl===undefined)delete process.env.DATABASE_URL;else process.env.DATABASE_URL=oldUrl;if(oldRequire===undefined)delete process.env.REQUIRE_POSTGRES;else process.env.REQUIRE_POSTGRES=oldRequire;}});
test('database outage health returns generic 503 without private errors',async()=>{const db=openDatabase(':memory:');const app=createApp({db,sessionSecret:'health-test-secret-at-least-32-characters'});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{const url=`http://127.0.0.1:${server.address().port}/api/health`;assert.equal((await fetch(url)).status,200);db.close();const response=await fetch(url);assert.equal(response.status,503);assert.equal((await response.json()).error.code,'DATABASE_UNAVAILABLE');}finally{await new Promise(r=>server.close(r));}});

test('Postgres pool enforces bounded deadlines, verified TLS and sanitized SQL timeout errors',async()=>{const {openPostgres}=await import('../src/db/postgres.js');const {errorHandler}=await import('../src/middleware/errorHandler.js');const old=process.env.DATABASE_AUTO_MIGRATE;process.env.DATABASE_AUTO_MIGRATE='0';let config;class Pool{constructor(value){config=value;}on(){}async query(){return{rows:[{}]};}async end(){}}let db;try{db=await openPostgres('postgresql://fixture:fixture@localhost/demo',{Pool,caFile:null,caCert:null});assert.equal(config.statement_timeout,15000);assert.equal(config.query_timeout,20000);assert.equal(config.ssl.rejectUnauthorized,true);for(const error of [Object.assign(new Error('private query contents'),{code:'57014'}),new Error('Query read timeout')]){const response={headersSent:false,status(value){this.statusCode=value;return this;},json(value){this.body=value;},setHeader(){}};errorHandler(error,{},response,()=>{});assert.equal(response.statusCode,503);assert.equal(response.body.error.code,'DATABASE_TIMEOUT');assert.ok(!response.body.error.message.includes('private'));}}finally{await db?.close();if(old===undefined)delete process.env.DATABASE_AUTO_MIGRATE;else process.env.DATABASE_AUTO_MIGRATE=old;}});
test('failed Postgres rollback preserves the original error and discards its connection',async()=>{const {openPostgres}=await import('../src/db/postgres.js');const old=process.env.DATABASE_AUTO_MIGRATE;process.env.DATABASE_AUTO_MIGRATE='0';let releasedWith;const original=new Error('fixture transaction failed');class Pool{on(){}async query(){return{rows:[]};}async connect(){return{async query(sql){if(sql==='ROLLBACK')throw new Error('connection lost');},release(error){releasedWith=error;}};}async end(){}}let db;try{db=await openPostgres('postgresql://fixture:fixture@localhost/demo',{Pool,caFile:null,caCert:null});await assert.rejects(db.transaction(async()=>{throw original;}),error=>error===original);assert.ok(releasedWith instanceof Error);}finally{await db?.close();if(old===undefined)delete process.env.DATABASE_AUTO_MIGRATE;else process.env.DATABASE_AUTO_MIGRATE=old;}});
