import test from 'node:test';
import assert from 'node:assert/strict';
import {openDatabase} from '../src/db/database.js';
import {PostgresSessionStore} from '../src/services/postgresSessionStore.js';
import {createPostgresLimits} from '../src/services/postgresRequestLimits.js';
function fixture(){const sqlite=openDatabase(':memory:');sqlite.exec('CREATE TABLE sessions(sid TEXT PRIMARY KEY,data TEXT NOT NULL,expires_at INTEGER);CREATE TABLE request_limits(bucket TEXT PRIMARY KEY,count INTEGER,resets_at INTEGER);');const deletes=[];let defer=false,fail=false;const execute=(sql,args)=>{const values=[];const statement=sql.replaceAll('novaworks.','').replaceAll('::jsonb','').replace(/\$(\d+)/g,(_,index)=>{values.push(args[Number(index)-1]);return '?';});const rows=sqlite.prepare(statement).all(...values).map(row=>row.data?{...row,data:JSON.parse(row.data)}:row);return{rows};};const db={query(sql,args=[]){if(sql.startsWith('DELETE')){const entry={sql,args};deletes.push(entry);if(fail)return Promise.reject(new Error('Fixture maintenance failure'));if(defer)return new Promise(resolve=>entry.complete=()=>resolve(execute(sql,args)));}return Promise.resolve(execute(sql,args));}};return{sqlite,db,deletes,setDeferred:value=>defer=value,setFailure:value=>fail=value};}
const get=(store,sid)=>new Promise((resolve,reject)=>store.get(sid,(error,value)=>error?reject(error):resolve(value)));
const settle=()=>new Promise(resolve=>setImmediate(resolve));
test('session cleanup removes only 100 expired records per minute and preserves refreshed rows',async()=>{const f=fixture();let clock=1000;try{const insert=f.sqlite.prepare('INSERT INTO sessions VALUES(?,?,?)');for(let i=0;i<102;i++)insert.run(`expired-${i}`,JSON.stringify({userId:'ADMIN'}),500);insert.run('active',JSON.stringify({userId:'DEV01'}),5000);f.setDeferred(true);const store=new PostgresSessionStore(f.db,{now:()=>clock});assert.equal((await get(store,'active')).userId,'DEV01');assert.equal(f.deletes.length,1);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM sessions').get().n,103);f.sqlite.prepare('UPDATE sessions SET expires_at=5000 WHERE sid=?').run('expired-0');f.deletes[0].complete();await settle();assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM sessions').get().n,3);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM sessions WHERE expires_at>1000').get().n,2);await get(store,'active');assert.equal(f.deletes.length,1);clock+=60000;f.setDeferred(false);await get(store,'active');await settle();assert.equal(f.deletes.length,2);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM sessions').get().n,0);}finally{f.sqlite.close();}});
test('quota maintenance is bounded, does not delay consumption and preserves reset buckets',async()=>{const f=fixture();let clock=1000;try{const insert=f.sqlite.prepare('INSERT INTO request_limits VALUES(?,?,?)');for(let i=0;i<101;i++)insert.run(`old-${i}`,1,500);insert.run('active-other',2,100000);f.setDeferred(true);const limits=createPostgresLimits(f.db,{aiDailyLimit:2,now:()=>clock});await limits.ai();assert.equal(f.deletes.length,1);f.sqlite.prepare('UPDATE request_limits SET resets_at=100000 WHERE bucket=?').run('old-0');f.deletes[0].complete();await settle();assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM request_limits').get().n,3);await limits.ai();assert.equal(f.deletes.length,1);await assert.rejects(limits.ai(),error=>error.status===429);clock+=60000;f.setDeferred(false);await assert.rejects(limits.ai(),error=>error.status===429);await settle();assert.equal(f.deletes.length,2);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM request_limits WHERE bucket IN (?,?)').get('active-other','old-0').n,2);}finally{f.sqlite.close();}});
test('maintenance errors never fail valid session reads or quota operations',async()=>{const f=fixture();let clock=1000;try{f.setFailure(true);f.sqlite.prepare('INSERT INTO sessions VALUES(?,?,?)').run('active',JSON.stringify({userId:'ADMIN'}),100000);const store=new PostgresSessionStore(f.db,{now:()=>clock});assert.equal((await get(store,'active')).userId,'ADMIN');const limits=createPostgresLimits(f.db,{now:()=>clock});await limits.ai();await settle();assert.equal(f.deletes.length,2);f.setFailure(false);clock+=60000;f.sqlite.prepare('INSERT INTO sessions VALUES(?,?,?)').run('expired',JSON.stringify({userId:'ADMIN'}),500);assert.equal((await get(store,'active')).userId,'ADMIN');await limits.ai();await settle();assert.equal(f.deletes.length,4);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM sessions WHERE sid=?').get('expired').n,0);}finally{f.sqlite.close();}});
