import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import http from 'node:http';
import {openDatabase} from '../src/db/database.js';
import {seedUsers} from '../src/db/seed.js';
import {createApp} from '../src/app.js';
import {validDate,validateAiOutput} from '../src/validators/aiOutput.js';
import {verifyPassword,hashPassword} from '../src/services/passwords.js';
import {extractProjects} from '../src/services/aiService.js';
import {createRequestLimits} from '../src/services/requestLimits.js';
import {teamDirectory,saveDraft} from '../src/services/projectService.js';
const fixture=JSON.parse(readFileSync(new URL('./fixtures/expected.json',import.meta.url)));
async function fixtureServer(work,options={}){const db=openDatabase(':memory:');seedUsers(db);const app=createApp({db,production:false,sessionSecret:'public-audit-fixture-session-secret-long-enough',...options});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;let cookie='';const request=async(path,body)=>{const res=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{...(cookie?{Cookie:cookie}:{}),...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});const set=res.headers.get('set-cookie');if(set)cookie=set.split(';')[0];return res;};try{await work({db,request});}finally{await new Promise(r=>server.close(r));db.close();}}
test('invalid URL encoding returns actionable client error without crashing valid sessions',async()=>{await fixtureServer(async({request})=>{assert.equal((await request('/api/auth/login',{email:'admin@novaworks.example',password:'Demo123!'})).status,200);const bad=await request('/api/projects/%ZZ');assert.equal(bad.status,400);assert.equal((await bad.json()).error.code,'BAD_PATH');assert.equal((await request('/api/auth/me')).status,200);});});
test('calendar year zero rejected before SQLite or Postgres persistence',()=>{assert.equal(validDate('0000-01-01'),false);assert.equal(validDate('0001-01-01'),true);assert.equal(validDate('2028-02-29'),true);const db=openDatabase(':memory:');try{seedUsers(db);const invalid=structuredClone(fixture);invalid.projects[0].deadline='0000-01-01';assert.throws(()=>validateAiOutput(invalid,teamDirectory(db)),e=>e.status===422);}finally{db.close();}});
test('malformed password hash fails closed and valid scrypt credentials still authenticate',()=>{for(const value of [null,undefined,12,{},'', 'scrypt:bad:bad', 'scrypt:'+ 'a'.repeat(32)+':'+ 'b'.repeat(128)+':unexpected'])assert.equal(verifyPassword('Demo123!',value),false);const hash=hashPassword('Demo123!');assert.equal(verifyPassword('Demo123!',hash),true);assert.equal(verifyPassword('wrong',hash),false);});
test('legacy CR-only and mixed-ending saved transcripts replay without provider spend',async()=>{let providerCalls=0;await fixtureServer(async({db,request})=>{await request('/api/auth/login',{email:'admin@novaworks.example',password:'Demo123!'});const transcripts=['CR-only meeting\rFinal decisions\rSave work','Mixed meeting\r\nFinal decisions\rSave work'];for(const transcript of transcripts){const hash=createHash('sha256').update(transcript.trim()).digest('hex');const saved=saveDraft(db,validateAiOutput(structuredClone(fixture),teamDirectory(db)),hash);const submitted=transcript.startsWith('CR-only')?transcript.replaceAll('\r','\n'):transcript;const response=await request('/api/admin/create-from-transcript',{transcript:submitted});assert.equal(response.status,200);const result=await response.json();assert.equal(result.replayed,true);assert.deepEqual(result.projects.map(p=>p.id),saved.projects.map(p=>p.id));}assert.equal(providerCalls,0);},{extract:async()=>{providerCalls++;return structuredClone(fixture);}});});
test('provider deadline covers stalled response body and gives sanitized timeout',async()=>{const server=http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'application/json'});res.write('{"choices":[');});server.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{await assert.rejects(extractProjects('Fixture transcript',[],{apiKey:'fixture-not-a-real-key',model:'fixture-model',baseUrl:`http://127.0.0.1:${server.address().port}`,timeoutMs:100}),e=>e.status===504&&e.code==='AI_TIMEOUT'&&!e.message.includes('fixture-not-a-real-key'));}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}});
test('SQLite quota check and increment cannot overspend under interleaved competing requests',()=>{const db=openDatabase(':memory:');const clock=Date.parse('2026-10-08T12:00:00Z');try{const competitor=createRequestLimits(db,{aiDailyLimit:1,now:()=>clock});let interleaved=false;const wrapped={exec:sql=>db.exec(sql),prepare(sql){const stmt=db.prepare(sql);if(sql.startsWith('SELECT count,resets_at')||sql.includes('RETURNING count'))return{get(...args){if(!interleaved){interleaved=true;if(sql.startsWith('SELECT')){const stale=stmt.get(...args);competitor.ai();return stale;}competitor.ai();}return stmt.get(...args);}};return stmt;}};const limiter=createRequestLimits(wrapped,{aiDailyLimit:1,now:()=>clock});assert.throws(()=>limiter.ai(),e=>e.status===429);assert.equal(db.prepare('SELECT count FROM request_limits').get().count,1);}finally{db.close();}});

test('all ten accounts get exactly their permitted project and task records',async()=>{await fixtureServer(async({db,request})=>{const saved=saveDraft(db,validateAiOutput(structuredClone(fixture),teamDirectory(db)),'all-roles-fixture');const users=db.prepare('SELECT id,email,role FROM users ORDER BY id').all();for(const user of users){const login=await request('/api/auth/login',{email:user.email,password:'Demo123!'});assert.equal(login.status,200);const projectsResponse=await request('/api/projects');const projects=(await projectsResponse.json()).projects;const tasks=(await (await request('/api/tasks')).json()).tasks;const expectedProjects=saved.projects.filter(project=>user.role==='ADMIN'||(user.role==='MANAGER'?project.managerId===user.id:project.tasks.some(task=>task.assigneeId===user.id)));assert.deepEqual(projects.map(p=>p.id).sort(),expectedProjects.map(p=>p.id).sort());const expectedTasks=saved.projects.flatMap(project=>project.tasks).filter(task=>user.role==='ADMIN'||(user.role==='MANAGER'?task.managerId===user.id:task.assigneeId===user.id));assert.deepEqual(tasks.map(t=>t.id).sort(),expectedTasks.map(t=>t.id).sort());for(const project of saved.projects){const detail=await request(`/api/projects/${project.id}`);if(!expectedProjects.some(p=>p.id===project.id)){assert.equal(detail.status,404);continue;}assert.equal(detail.status,200);const value=await detail.json();assert.ok(value.tasks.every(task=>user.role!=='AGENT'||task.assigneeId===user.id));}assert.equal((await request('/api/auth/logout',{})).status,200);assert.equal((await request('/api/auth/me')).status,401);}});});
test('login regenerates session identity and invalidates the previous account cookie',async()=>{const db=openDatabase(':memory:');seedUsers(db);const app=createApp({db,production:false,sessionSecret:'session-regeneration-audit-secret-long-enough'});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;try{const login=async(email,cookie)=>fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:JSON.stringify({email,password:'Demo123!'})});const first=await login('admin@novaworks.example');const oldCookie=first.headers.get('set-cookie').split(';')[0];const second=await login('ali@novaworks.example',oldCookie);const newCookie=second.headers.get('set-cookie').split(';')[0];assert.notEqual(oldCookie,newCookie);assert.equal((await fetch(base+'/api/auth/me',{headers:{Cookie:oldCookie}})).status,401);const identity=await fetch(base+'/api/auth/me',{headers:{Cookie:newCookie}});assert.equal((await identity.json()).id,'DEV01');}finally{await new Promise(r=>server.close(r));db.close();}});

test('AI fields with database-incompatible NUL characters are rejected before saving',()=>{const db=openDatabase(':memory:');try{seedUsers(db);const mutations=[draft=>draft.projects[0].name='Urban\u0000Cart',draft=>draft.projects[0].clientName='Client\u0000name',draft=>draft.projects[0].description='Project\u0000description',draft=>draft.projects[0].tasks[0].title='Task\u0000title',draft=>draft.projects[0].tasks[0].description='Task\u0000description'];for(const mutate of mutations){const draft=structuredClone(fixture);mutate(draft);assert.throws(()=>validateAiOutput(draft,teamDirectory(db)),error=>error.status===422);assert.equal(db.prepare('SELECT COUNT(*) n FROM projects').get().n,0);}}finally{db.close();}});
