BEGIN;
CREATE SCHEMA IF NOT EXISTS novaworks;
REVOKE ALL ON SCHEMA novaworks FROM PUBLIC,anon,authenticated;
CREATE TABLE IF NOT EXISTS novaworks.users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('ADMIN','MANAGER','AGENT')),specialization TEXT NOT NULL,skills JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS novaworks.projects(id TEXT PRIMARY KEY,name TEXT NOT NULL,client_name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',manager_id TEXT REFERENCES novaworks.users(id) NOT NULL,deadline DATE NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS novaworks.tasks(id TEXT PRIMARY KEY,project_id TEXT REFERENCES novaworks.projects(id) ON DELETE CASCADE NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',assignee_id TEXT REFERENCES novaworks.users(id) NOT NULL,deadline DATE NOT NULL,estimated_hours DOUBLE PRECISION NOT NULL CHECK(estimated_hours>0 AND estimated_hours<'Infinity'::float8),created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS novaworks.transcript_submissions(hash TEXT PRIMARY KEY,result_json JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS novaworks.sessions(sid TEXT PRIMARY KEY,data JSONB NOT NULL,expires_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS novaworks.request_limits(bucket TEXT PRIMARY KEY,count INTEGER NOT NULL,resets_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS projects_manager ON novaworks.projects(manager_id);
CREATE INDEX IF NOT EXISTS tasks_project ON novaworks.tasks(project_id);
CREATE INDEX IF NOT EXISTS tasks_assignee ON novaworks.tasks(assignee_id);
CREATE INDEX IF NOT EXISTS sessions_expiry ON novaworks.sessions(expires_at);
CREATE OR REPLACE FUNCTION novaworks.check_project_manager() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN IF NOT EXISTS(SELECT 1 FROM novaworks.users WHERE id=NEW.manager_id AND role='MANAGER') THEN RAISE EXCEPTION 'Project manager must be a MANAGER'; END IF; RETURN NEW; END $$;
CREATE OR REPLACE FUNCTION novaworks.check_task() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN IF NOT EXISTS(SELECT 1 FROM novaworks.users WHERE id=NEW.assignee_id AND role='AGENT') THEN RAISE EXCEPTION 'Task assignee must be an AGENT'; END IF; IF NEW.deadline>(SELECT deadline FROM novaworks.projects WHERE id=NEW.project_id) THEN RAISE EXCEPTION 'Task deadline exceeds project deadline'; END IF; RETURN NEW; END $$;
DROP TRIGGER IF EXISTS project_manager_role ON novaworks.projects;
CREATE TRIGGER project_manager_role BEFORE INSERT OR UPDATE ON novaworks.projects FOR EACH ROW EXECUTE FUNCTION novaworks.check_project_manager();
DROP TRIGGER IF EXISTS task_validity ON novaworks.tasks;
CREATE TRIGGER task_validity BEFORE INSERT OR UPDATE ON novaworks.tasks FOR EACH ROW EXECUTE FUNCTION novaworks.check_task();
ALTER TABLE novaworks.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE novaworks.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE novaworks.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE novaworks.transcript_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE novaworks.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE novaworks.request_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA novaworks FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA novaworks FROM PUBLIC,anon,authenticated;
COMMIT;
