import React, { useEffect, useRef, useState } from 'react';
import { request } from './api.js';
import DemoAccounts from './DemoAccounts.jsx';
import { previewUsers, previewProjects, previewTasks } from './preview.js';

const isPreview = new URLSearchParams(window.location.search).get('preview') === '1';
const roles = { ADMIN: 'Administrator', MANAGER: 'Project manager', AGENT: 'Developer' };
const date = value => { if (!value) return 'Not set'; const d = new Date(`${value.slice(0,10)}T12:00:00`); return Number.isNaN(d.valueOf()) ? value : new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(d); };
function Brand() { return <a className="brand" href={isPreview ? '/?preview=1' : '/'} aria-label="NovaWorks home"><span className="brand-symbol" aria-hidden="true">N</span><span><strong>NovaWorks</strong><small>Meeting to Execution</small></span></a>; }
function ErrorNotice({ error }) { if (!error) return null; return <div className="notice error" role="alert"><strong>{error.message}</strong>{error.issues?.length > 0 && <ul>{error.issues.map((i,n)=><li key={n}>{i.field ? `${i.field}: ` : ''}{i.message || String(i)}</li>)}</ul>}</div>; }
function Empty({ title, children }) { return <div className="empty"><div className="empty-mark" aria-hidden="true">—</div><h2>{title}</h2><p>{children}</p></div>; }
function Login({ onLogin, notice }) {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(null); const pending=useRef(false);
  async function submit(e) { e.preventDefault(); if(pending.current)return; pending.current=true; setBusy(true); setError(null); try { const {user}=await request('/auth/login',{method:'POST',body:{email,password}}); onLogin(user); } catch(e) {setError(e);} finally {pending.current=false;setBusy(false);} }
  return <div className="login-page"><header className="login-header"><Brand /><span className="company-location">NovaWorks Technologies · Lahore</span></header><main id="main" className="login-main"><section className="login-context"><p className="context-line">Your meeting has ended.<br />The work starts here.</p><p>Turn agreed decisions into projects, owners and deadlines. Keep every team member focused on their assigned work.</p><div className="login-process"><span>Meeting transcript</span><span aria-hidden="true">→</span><span>Assigned work</span></div></section><section className="login-form"><h1>Sign in to your workspace</h1><p className="muted">Use your supplied NovaWorks demo account.</p><form onSubmit={submit}><label htmlFor="email">Email address</label><input id="email" type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@novaworks.example" required /><label htmlFor="password">Password</label><input id="password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required /><ErrorNotice error={error || notice}/><button className="primary full" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form><DemoAccounts disabled={busy} onSelect={account=>{setEmail(account.email);setPassword(account.password);setError(null);}}/><p className="login-note">Accounts are already set up. No signup is needed.</p></section></main><footer className="login-footer">Client delivery planning, with a clear next step.</footer></div>;
}
function Tasks({ tasks, showProject, openProject }) { return <div className="task-table"><div className="task-head" aria-hidden="true"><span>Task & scope</span><span>Assigned to</span><span>Deadline</span><span>Effort</span></div>{tasks.map(t=><article className="task-row" key={t.id}><div className="task-content">{showProject && <button className="project-link" onClick={()=>openProject(t.projectId)}>{t.projectName || 'Open project'}</button>}<h3>{t.title}</h3><p>{t.description || 'No description provided.'}</p></div><div className="task-owner"><span className="mobile-label">Assigned to</span>{t.assigneeName || t.assigneeId}</div><div><span className="mobile-label">Deadline</span><time dateTime={t.deadline}>{date(t.deadline)}</time></div><div className="hours"><span className="mobile-label">Effort</span>{t.estimatedHours} <span>hours</span></div></article>)}</div>; }
export default function App() {
  const [user,setUser]=useState(isPreview?previewUsers[0]:null); const [checking,setChecking]=useState(!isPreview); const [view,setView]=useState('projects'); const [projectId,setProjectId]=useState(null); const [data,setData]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(null); const [version,setVersion]=useState(0);
  const [sampleLoading,setSampleLoading]=useState(false); const sampleController=useRef(null);
  const [composer,setComposer]=useState(false); const [transcript,setTranscript]=useState(''); const [creating,setCreating]=useState(false); const [createError,setCreateError]=useState(null); const [success,setSuccess]=useState(''); const [loggingOut,setLoggingOut]=useState(false); const createPending=useRef(false); const createController=useRef(null); const heading=useRef(null);
  function resetSession(expired=false){sampleController.current?.abort();sampleController.current=null;setSampleLoading(false);createController.current?.abort();createController.current=null;createPending.current=false;setCreating(false);setUser(null);setData(null);setProjectId(null);setTranscript('');setComposer(false);setCreateError(null);setSuccess('');setError(expired?{message:'Your session has expired. Sign in again to continue.'}:null);}
  useEffect(()=>{if(isPreview)return;const c=new AbortController();request('/auth/me',{signal:c.signal}).then(({user})=>{setUser(user);setView(user.role==='AGENT'?'tasks':'projects');}).catch(e=>{if(e.name!=='AbortError'&&e.status!==401)setError(e);}).finally(()=>{if(!c.signal.aborted)setChecking(false);});return()=>c.abort();},[]);
  useEffect(()=>{
    if(!user)return; const c=new AbortController();setData(null);setError(null);setLoading(true);
    if(isPreview){const tasks=user.role==='AGENT'?previewTasks.filter(t=>t.assigneeId===user.id):previewTasks; const projects=previewProjects.filter(p=>user.role==='ADMIN'||(user.role==='MANAGER'?p.managerId===user.id:tasks.some(t=>t.projectId===p.id))); const project=projects.find(p=>p.id===projectId); setData(view==='team'?{users:previewUsers}:view==='detail'?{project,tasks:tasks.filter(t=>t.projectId===projectId)}:view==='tasks'?{tasks}:{projects});setLoading(false);return()=>c.abort();}
    const path=view==='team'?'/team':view==='tasks'?'/tasks/mine':view==='detail'?`/projects/${encodeURIComponent(projectId)}`:'/projects';
    request(path,{signal:c.signal}).then(setData).catch(e=>{if(e.name==='AbortError')return;if(e.status===401){resetSession(true);return;}setError(e);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();
  },[user,view,projectId,version]);
  useEffect(()=>{heading.current?.focus();},[view,projectId]);
  useEffect(()=>()=>sampleController.current?.abort(),[]);
  function navigate(next,id=null){setView(next);setProjectId(id);setError(null);}
  async function loadSample(){
    if(transcript.length || sampleController.current || creating)return;
    const controller=new AbortController();sampleController.current=controller;setSampleLoading(true);setCreateError(null);
    try{
      const response=await fetch('/sample-meeting.txt',{signal:controller.signal});
      if(!response.ok)throw new Error('Could not load the sample meeting. Paste your own transcript or try again.');
      const text=(await response.text()).replace(/\r\n?/g,'\n');
      if(!text.trim() || text.length>100000 || !text.startsWith('Meeting: NovaWorks'))throw new Error('The sample meeting is unavailable. Paste your own transcript or try again.');
      if(!controller.signal.aborted)setTranscript(text);
    }catch(error){if(error.name!=='AbortError')setCreateError({message:error.message || 'Could not load the sample meeting. Please try again.'});}
    finally{if(sampleController.current===controller){sampleController.current=null;setSampleLoading(false);}}
  }
  function authenticated(u){setData(null);setProjectId(null);setComposer(false);setCreateError(null);setSuccess('');setUser(u);setView(u.role==='AGENT'?'tasks':'projects');setError(null);}
  async function logout(){setLoggingOut(true);try{if(!isPreview)await request('/auth/logout',{method:'POST'});resetSession();}catch(e){if(e.status===401)resetSession();else setError(e);}finally{setLoggingOut(false);}}
  async function create(e){e.preventDefault();if(createPending.current)return;setCreateError(null);setSuccess('');if(isPreview){setCreateError({message:'Interface preview only. Open the live workspace to process a transcript. No records were created.'});return;}createPending.current=true;setCreating(true);const c=new AbortController();createController.current=c;try{const result=await request('/transcripts',{method:'POST',body:{transcript},signal:c.signal});if(c.signal.aborted)return;setSuccess(result.replayed ? `This meeting was already saved. Showing its existing ${result.projectCount} projects and ${result.taskCount} tasks; no duplicate records were created.` : `${result.projectCount} projects and ${result.taskCount} tasks saved. Open a project to review the assigned work.`);setComposer(false);setTranscript('');setVersion(v=>v+1);}catch(e){if(e.name==='AbortError')return;if(e.status===401)resetSession(true);else setCreateError(e);}finally{if(createController.current===c){createController.current=null;createPending.current=false;setCreating(false);}}}
  const title=view==='team'?'Team directory':view==='tasks'?'My tasks':view==='detail'?(data?.project?.name || 'Project details'):'Projects';
  if(checking)return <main className="startup"><Brand/><p role="status">Opening your workspace…</p></main>;
  if(!user)return <><a className="skip" href="#main">Skip to content</a><Login onLogin={authenticated} notice={error}/></>;
  return <><a className="skip" href="#main">Skip to content</a>{isPreview&&<div className="preview-bar"><strong>Interface preview — static sample data. No login, AI or saved records.</strong><label>View as <select value={user.id} onChange={e=>{authenticated(previewUsers.find(u=>u.id===e.target.value));setComposer(false);setSuccess('');setCreateError(null);}}>{previewUsers.map(u=><option value={u.id} key={u.id}>{u.name} · {roles[u.role]}</option>)}</select></label><a href="/">Open live workspace</a></div>}
    <header className="app-header"><div className="header-inner"><Brand/><div className="account"><div><strong>{user.name}</strong><span>{roles[user.role]}</span></div><button className="quiet" onClick={logout} disabled={loggingOut||creating}>{loggingOut?'Signing out…':'Sign out'}</button></div></div></header>
    <div className="workspace"><aside className="sidebar"><nav aria-label="Workspace">{user.role==='AGENT'&&<button aria-current={view==='tasks'?'page':undefined} onClick={()=>navigate('tasks')}>My tasks</button>}<button aria-current={view==='projects'||view==='detail'?'page':undefined} onClick={()=>navigate('projects')}>Projects</button><button aria-current={view==='team'?'page':undefined} onClick={()=>navigate('team')}>Team directory</button></nav><div className="sidebar-note"><strong>Clear ownership.<br/>Agreed deadlines.</strong><p>{user.role==='ADMIN'?'Create work from the meeting. Your team sees their assignments.':'Your workspace shows only the work assigned to you.'}</p></div></aside>
    <main id="main" className="main-content" aria-busy={loading}><div className="page-heading"><div>{view==='detail'&&<button className="back" onClick={()=>navigate('projects')}>← Back to projects</button>}<h1 ref={heading} tabIndex={-1}>{title}</h1><p className="muted">{view==='team'?'The people available for project and task assignments.':view==='tasks'?'Your assigned work, with the scope and deadline in one place.':view==='detail'?'Agreed scope and assigned work.':user.role==='ADMIN'?'Turn meeting decisions into a clear delivery plan.':'The client work you are assigned to.'}</p></div>{view==='projects'&&user.role==='ADMIN'&&<button className={composer?'secondary':'primary'} aria-expanded={composer} aria-controls="transcript-panel" onClick={()=>{setComposer(v=>!v);setCreateError(null);}} disabled={creating}>{composer?'Close transcript':'Create from Transcript'}</button>}</div>
    {success&&<div className="notice success" role="status"><strong>Work is ready.</strong><p>{success}</p></div>}
    {view==='projects'&&composer&&<section id="transcript-panel" className="transcript-panel"><div className="composer-heading"><h2>From meeting to assigned work</h2><p>Paste the complete meeting. Final agreed decisions become saved projects and tasks.</p></div><div className="sample-tools"><button type="button" className="secondary" onClick={loadSample} disabled={creating||sampleLoading||transcript.length>0}>{sampleLoading?'Loading sample…':'Load sample meeting'}</button><p id="sample-help">A fictional client-planning meeting. Loading it does not process or save anything. Clear the field before loading a sample.</p></div><form onSubmit={create}><label htmlFor="transcript">Meeting description or transcript</label><textarea id="transcript" rows="10" maxLength={100000} aria-describedby="sample-help transcript-count" placeholder="Paste the full meeting here, including corrections and final decisions…" value={transcript} onChange={e=>setTranscript(e.target.value)} required disabled={creating||sampleLoading}/><div className="transcript-meta"><span id="transcript-count">{transcript.length.toLocaleString()} / 100,000 characters</span><button type="button" className="quiet" disabled={creating||sampleLoading||!transcript.length} onClick={()=>{setTranscript('');setCreateError(null);}}>Clear transcript</button></div><ErrorNotice error={createError}/><div className="composer-footer"><p>{creating?'Processing the meeting. Projects and tasks are saved together after validation.':'Unclear required information will be returned for correction.'}</p><button className="primary" disabled={creating||sampleLoading||!transcript.trim()}>{creating?'Creating projects…':'Create projects and tasks'}</button></div><div className="sr-only" role="status">{creating?'Processing transcript. Please wait.':''}</div></form></section>}
    <ErrorNotice error={error}/>{loading&&<div className="loading" role="status">Loading {view==='detail'?'project':title.toLowerCase()}…</div>}
    {!loading&&!error&&data&&view==='projects'&&(data.projects?.length?<div className="project-grid">{data.projects.map(p=><button className="project-card" key={p.id} onClick={()=>navigate('detail',p.id)}><span className="client-name">{p.clientName}</span><h2>{p.name}</h2><p>{p.description || 'Open the project to review scope and assignments.'}</p><dl><div><dt>Project manager</dt><dd>{p.managerName || p.managerId}</dd></div><div><dt>Delivery deadline</dt><dd><time dateTime={p.deadline}>{date(p.deadline)}</time></dd></div></dl><span className="open-project">Open project <span aria-hidden="true">↗</span></span></button>)}</div>:<Empty title={user.role==='ADMIN'?'Start with the meeting':'No assigned projects yet'}>{user.role==='ADMIN'?'Use Create from Transcript to turn agreed decisions into saved projects and tasks.':'Projects will appear here when work is assigned to you.'}</Empty>)}
    {!loading&&!error&&data&&view==='detail'&&(data.project?<><section className="project-summary"><p className="client-name">{data.project.clientName}</p><p className="scope">{data.project.description}</p><dl><div><dt>Project manager</dt><dd>{data.project.managerName || data.project.managerId}</dd></div><div><dt>Delivery deadline</dt><dd>{date(data.project.deadline)}</dd></div></dl></section><div className="section-heading"><h2>{user.role==='AGENT'?'Your tasks':'Assigned tasks'}</h2><span>{data.tasks?.length || 0} tasks</span></div>{data.tasks?.length?<Tasks tasks={data.tasks}/>:<Empty title="No tasks to show">There are no assigned tasks available in this project.</Empty>}</>:<Empty title="Project unavailable">Return to projects to view work you can access.</Empty>)}
    {!loading&&!error&&data&&view==='tasks'&&(data.tasks?.length?<Tasks tasks={data.tasks} showProject openProject={id=>navigate('detail',id)}/>:<Empty title="No assigned tasks yet">Your assigned tasks will appear here with their scope, deadline and estimated hours.</Empty>)}
    {!loading&&!error&&data&&view==='team'&&<div className="directory"><div className="directory-head"><span>Team member</span><span>Specialization</span></div>{data.users?.map(u=><div className="directory-row" key={u.id}><div className="person"><span className="initials" aria-hidden="true">{u.name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><div><strong>{u.name}</strong><span>{roles[u.role] || u.role}</span></div></div><span>{u.specialization || 'Not specified'}</span></div>)}</div>}
    {!loading&&error&&<button className="secondary" onClick={()=>setVersion(v=>v+1)}>Try again</button>}
    <footer className="workspace-footer">NovaWorks Technologies<span>Meeting to Execution</span></footer></main></div></>;
}
