import React, { useEffect, useRef, useState } from 'react';
import { request } from './api.js';
import { formatDate as date } from './formatDate.js';
import DemoAccounts from './DemoAccounts.jsx';
import { ProjectList, TaskList, DirectoryList } from './WorkLists.jsx';
import { previewUsers, previewProjects, previewTasks } from './preview.js';

const isPreview = new URLSearchParams(window.location.search).get('preview') === '1';
function NavigationIcon({ name }) {
  const paths = { projects: 'M3 5h6l2 2h10v13H3V5Z', tasks: 'm4 7 2 2 4-4M13 7h7M4 16l2 2 4-4M13 16h7', team: 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M17 4a4 4 0 0 1 0 8M22 21v-2a4 4 0 0 0-3-3.87' };
  return <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>;
}
const roles = { ADMIN: 'Administrator', MANAGER: 'Project manager', AGENT: 'Developer' };
function Brand() { return <a className="brand" href={isPreview ? '/?preview=1' : '/'} aria-label="NovaWorks Meeting to Execution home"><span className="brand-symbol" aria-hidden="true">N</span><span><strong>NovaWorks</strong><small>Meeting to Execution</small></span></a>; }
function ErrorNotice({ error, id }) { if (!error) return null; return <div id={id} className="notice error" role="alert"><strong>{error.message}</strong>{error.issues?.length > 0 && <ul>{error.issues.map((i,n)=><li key={n}>{i.field ? `${i.field}: ` : ''}{i.message || String(i)}</li>)}</ul>}</div>; }
function Empty({ title, children }) { return <div className="empty"><div className="empty-mark" aria-hidden="true">—</div><h2>{title}</h2><p>{children}</p></div>; }
function Login({ onLogin, notice }) {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(null); const pending=useRef(false);
  async function submit(e) { e.preventDefault(); if(pending.current)return; pending.current=true; setBusy(true); setError(null); try { const {user}=await request('/auth/login',{method:'POST',body:{email:email.trim(),password}}); onLogin(user); } catch(e) {setError(e);} finally {pending.current=false;setBusy(false);} }
  return <div className="login-page"><header className="login-header"><Brand /><span className="company-location">NovaWorks Technologies · Lahore</span></header><main id="main" className="login-main"><section className="login-context"><p className="login-eyebrow">Meeting to execution</p><p className="context-line">Clear decisions.<br />Assigned work.</p><p>Turn agreed decisions into projects, owners and deadlines. Keep every team member focused on their assigned work.</p><div className="login-process"><span>Meeting transcript</span><span aria-hidden="true">→</span><span>Assigned work</span></div><DemoAccounts disabled={busy} selectedEmail={email} onSelect={account=>{setEmail(account.email);setPassword(account.password);setError(null);}}/></section><section className="login-form"><h1>Sign in to your workspace</h1><p className="muted">Choose a demo role or enter your supplied account.</p><p className="sr-only" role="status">{busy?'Signing in. Please wait.':''}</p><form onSubmit={submit} aria-busy={busy}><label htmlFor="email">Email address</label><input id="email" type="email" disabled={busy} aria-invalid={error?.status===401 || undefined} aria-describedby={error || notice ? 'login-error' : undefined} autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@novaworks.example" required /><label htmlFor="password">Password</label><input id="password" type="password" disabled={busy} aria-invalid={error?.status===401 || undefined} aria-describedby={error || notice ? 'login-error' : undefined} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required /><ErrorNotice error={error || notice} id="login-error"/><button className="primary full" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form><p className="login-note">Accounts are already set up. No signup is needed.</p></section></main><footer className="login-footer">Client delivery planning, with a clear next step.</footer></div>;
}
export default function App() {
  const [user,setUser]=useState(isPreview?previewUsers[0]:null); const [checking,setChecking]=useState(!isPreview); const [view,setView]=useState('projects'); const [projectId,setProjectId]=useState(null); const [data,setData]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(null); const [version,setVersion]=useState(0);
  const [menuOpen,setMenuOpen]=useState(false); const menuButton=useRef(null);
  const [sampleLoading,setSampleLoading]=useState(false); const sampleController=useRef(null);
  const [composer,setComposer]=useState(false); const [transcript,setTranscript]=useState(''); const [creating,setCreating]=useState(false); const [createError,setCreateError]=useState(null); const [success,setSuccess]=useState(''); const [loggingOut,setLoggingOut]=useState(false); const createPending=useRef(false); const createController=useRef(null); const heading=useRef(null); const transcriptInput=useRef(null);
  function resetSession(expired=false){setMenuOpen(false);sampleController.current?.abort();sampleController.current=null;setSampleLoading(false);createController.current?.abort();createController.current=null;createPending.current=false;setCreating(false);setUser(null);setData(null);setProjectId(null);setTranscript('');setComposer(false);setCreateError(null);setSuccess('');setError(expired?{message:'Your session has expired. Sign in again to continue.'}:null);}
  useEffect(()=>{if(isPreview)return;const c=new AbortController();request('/auth/me',{signal:c.signal}).then(({user})=>{if(c.signal.aborted)return;setUser(user);setView(user.role==='AGENT'?'tasks':'projects');}).catch(e=>{if(!c.signal.aborted&&e.name!=='AbortError'&&e.status!==401)setError(e);}).finally(()=>{if(!c.signal.aborted)setChecking(false);});return()=>c.abort();},[]);
  useEffect(()=>{
    if(!user)return; const c=new AbortController();setData(null);setError(null);setLoading(true);
    if(isPreview){const tasks=user.role==='AGENT'?previewTasks.filter(t=>t.assigneeId===user.id):previewTasks; const projects=previewProjects.filter(p=>user.role==='ADMIN'||(user.role==='MANAGER'?p.managerId===user.id:tasks.some(t=>t.projectId===p.id))); const project=projects.find(p=>p.id===projectId); setData(view==='team'?{users:previewUsers}:view==='detail'?{project,tasks:tasks.filter(t=>t.projectId===projectId)}:view==='tasks'?{tasks}:{projects});setLoading(false);return()=>c.abort();}
    const path=view==='team'?'/team':view==='tasks'?'/tasks/mine':view==='detail'?`/projects/${encodeURIComponent(projectId)}`:'/projects';
    request(path,{signal:c.signal}).then(result=>{if(!c.signal.aborted)setData(result);}).catch(e=>{if(c.signal.aborted||e.name==='AbortError')return;if(e.status===401){resetSession(true);return;}setError(e);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();
  },[user,view,projectId,version]);
  useEffect(()=>{heading.current?.focus();},[view,projectId,user?.id,checking]);
  useEffect(()=>{if(composer&&view==='projects')transcriptInput.current?.focus();},[composer,view]);
  useEffect(()=>{const query=window.matchMedia('(min-width: 1025px)');const close=()=>setMenuOpen(false);query.addEventListener('change',close);return()=>query.removeEventListener('change',close);},[]);
  useEffect(()=>{if(!menuOpen)return;const escape=e=>{if(e.key==='Escape'){setMenuOpen(false);menuButton.current?.focus();}};document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape);},[menuOpen]);
  useEffect(()=>()=>{sampleController.current?.abort();createController.current?.abort();},[]);
  function navigate(next,id=null){setMenuOpen(false);setView(next);setProjectId(id);setError(null);}
  async function loadSample(){
    if(transcript.length || sampleController.current || creating)return;
    const controller=new AbortController();sampleController.current=controller;setSampleLoading(true);setCreateError(null);
    let timedOut=false;const timer=setTimeout(()=>{timedOut=true;controller.abort();},15000);
    try{
      const response=await fetch('/sample-meeting.txt',{signal:controller.signal});
      if(!response.ok)throw new Error('Could not load the sample meeting. Paste your own transcript or try again.');
      const text=(await response.text()).replace(/\r\n?/g,'\n');
      if(!text.trim() || text.length>100000 || !text.startsWith('Meeting: NovaWorks'))throw new Error('The sample meeting is unavailable. Paste your own transcript or try again.');
      if(!controller.signal.aborted)setTranscript(text);
    }catch(error){if(timedOut)setCreateError({message:'The sample meeting took too long to load. Try again or paste your own transcript.'});else if(!controller.signal.aborted&&error.name!=='AbortError')setCreateError({message:'Could not load the sample meeting. Paste your own transcript or try again.'});}
    finally{clearTimeout(timer);if(sampleController.current===controller){sampleController.current=null;setSampleLoading(false);}}
  }
  function authenticated(u){setMenuOpen(false);setData(null);setProjectId(null);setComposer(false);setCreateError(null);setSuccess('');setUser(u);setView(u.role==='AGENT'?'tasks':'projects');setError(null);}
  async function logout(){setLoggingOut(true);try{if(!isPreview)await request('/auth/logout',{method:'POST'});resetSession();}catch(e){if(e.status===401)resetSession();else setError(e);}finally{setLoggingOut(false);}}
  async function create(e){e.preventDefault();if(createPending.current)return;setCreateError(null);setSuccess('');if(isPreview){setCreateError({message:'Interface preview only. Open the live workspace to process a transcript. No records were created.'});return;}createPending.current=true;setCreating(true);const c=new AbortController();createController.current=c;try{const result=await request('/transcripts',{method:'POST',body:{transcript},signal:c.signal});if(c.signal.aborted)return;setSuccess(result.replayed ? `This meeting was already saved. Showing its existing ${result.projectCount} projects and ${result.taskCount} tasks; no duplicate records were created.` : `${result.projectCount} projects and ${result.taskCount} tasks saved. Open a project to review the assigned work.`);setComposer(false);setTranscript('');setVersion(v=>v+1);}catch(e){if(e.name==='AbortError')return;if(e.status===401)resetSession(true);else setCreateError(e);}finally{if(createController.current===c){createController.current=null;createPending.current=false;setCreating(false);}}}
  const title=view==='team'?'Team directory':view==='tasks'?'My tasks':view==='detail'?(data?.project?.name || 'Project details'):'Projects';
  if(checking)return <main className="startup"><Brand/><p role="status">Opening your workspace…</p></main>;
  if(!user)return <><a className="skip" href="#main">Skip to content</a><Login onLogin={authenticated} notice={error}/></>;
  return <><a className="skip" href="#main">Skip to content</a>{isPreview&&<div className="preview-bar"><strong>Interface preview — static sample data. No login, AI or saved records.</strong><label>View as <select value={user.id} onChange={e=>{authenticated(previewUsers.find(u=>u.id===e.target.value));setComposer(false);setSuccess('');setCreateError(null);}}>{previewUsers.map(u=><option value={u.id} key={u.id}>{u.name} · {roles[u.role]}</option>)}</select></label><a href="/">Open live workspace</a></div>}
    <header className="app-header"><div className="header-inner"><div className="header-identity"><button ref={menuButton} className="menu-toggle quiet" aria-label="Menu" aria-expanded={menuOpen} aria-controls="workspace-navigation" onClick={()=>setMenuOpen(v=>!v)}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" aria-hidden="true"><path d={menuOpen?'M6 6l12 12M6 18 18 6':'M4 6h16M4 12h16M4 18h16'}/></svg><span>Menu</span></button><Brand/></div><div className="account"><div><strong>{user.name}</strong><span>{roles[user.role]}</span></div><button className="quiet" onClick={logout} disabled={loggingOut||creating}>{loggingOut?'Signing out…':'Sign out'}</button></div></div></header>
    <div className="workspace"><aside id="workspace-navigation" className={'sidebar'+(menuOpen?' is-open':'')}><div className="rail-context"><span>Workspace</span><strong>{roles[user.role]}</strong></div><nav aria-label="Workspace">{user.role==='AGENT'&&<button aria-current={view==='tasks'?'page':undefined} onClick={()=>navigate('tasks')}><NavigationIcon name="tasks"/>My tasks</button>}<button aria-current={view==='projects'||view==='detail'?'page':undefined} onClick={()=>navigate('projects')}><NavigationIcon name="projects"/>Projects</button><button aria-current={view==='team'?'page':undefined} onClick={()=>navigate('team')}><NavigationIcon name="team"/>Team directory</button></nav><div className="sidebar-note"><strong>Meeting to execution</strong><p>{user.role==='ADMIN'?'Create work from the meeting. Your team sees their assignments.':'Your workspace shows only the work assigned to you.'}</p></div></aside>
    <main id="main" className="main-content" aria-busy={loading}><div className="page-heading"><div>{view==='detail'&&<button className="back" onClick={()=>navigate('projects')}>← Back to projects</button>}<h1 ref={heading} tabIndex={-1}>{title}</h1><p className="muted">{view==='team'?'The people available for project and task assignments.':view==='tasks'?'Your assigned work, with the scope and deadline in one place.':view==='detail'?'Agreed scope and assigned work.':user.role==='ADMIN'?'Turn meeting decisions into a clear delivery plan.':'The client work you are assigned to.'}</p></div>{view==='projects'&&user.role==='ADMIN'&&<button className={composer?'secondary':'primary'} aria-expanded={composer} aria-controls="transcript-panel" onClick={()=>{setComposer(v=>!v);setCreateError(null);}} disabled={creating}>{composer?'Close transcript':'Create from Transcript'}</button>}</div>
    {success&&<div className="notice success" role="status"><strong>Work is ready.</strong><p>{success}</p></div>}
    {view==='projects'&&composer&&<section id="transcript-panel" className="transcript-panel"><div className="composer-heading"><h2>From meeting to assigned work</h2><p>Paste the complete meeting. Final agreed decisions become saved projects and tasks.</p></div><div className="sample-tools"><button type="button" className="secondary" onClick={loadSample} disabled={creating||sampleLoading||transcript.length>0}>{sampleLoading?'Loading sample…':'Load sample meeting'}</button><p id="sample-help">A fictional client-planning meeting. Loading it does not process or save anything. Clear the field before loading a sample.</p></div><form onSubmit={create}><label htmlFor="transcript">Meeting description or transcript</label><textarea id="transcript" ref={transcriptInput} rows="10" maxLength={100000} aria-describedby={'sample-help transcript-count'+(createError?' transcript-error':'')} aria-invalid={[400,422].includes(createError?.status) || undefined} placeholder="Paste the full meeting here, including corrections and final decisions…" value={transcript} onChange={e=>setTranscript(e.target.value)} required disabled={creating||sampleLoading}/><div className="transcript-meta"><span id="transcript-count">{transcript.length.toLocaleString()} / 100,000 characters</span><button type="button" className="quiet" disabled={creating||sampleLoading||!transcript.length} onClick={()=>{setTranscript('');setCreateError(null);}}>Clear transcript</button></div><ErrorNotice error={createError} id="transcript-error"/><div className="composer-footer"><p>{creating?'Processing the meeting. Projects and tasks are saved together after validation.':'Unclear required information will be returned for correction.'}</p><button className="primary" disabled={creating||sampleLoading||!transcript.trim()}>{creating?'Creating projects…':'Create projects and tasks'}</button></div><div className="sr-only" role="status">{creating?'Processing transcript. Please wait.':''}</div></form></section>}
    <ErrorNotice error={error}/>{view!=='projects'&&creating&&<p className="notice pending" role="status">Processing your meeting. You can return to Projects to view the result.</p>}{view!=='projects'&&createError&&<div className="creation-recovery"><ErrorNotice error={createError}/><button className="secondary" onClick={()=>navigate('projects')}>Return to transcript</button></div>}{loading&&<div className="loading" role="status">Loading {view==='detail'?'project':title.toLowerCase()}…</div>}
    {!loading&&!error&&data&&view==='projects'&&(data.projects?.length?<ProjectList projects={data.projects} openProject={id=>navigate('detail',id)}/>:<Empty title={user.role==='ADMIN'?'Start with the meeting':'No assigned projects yet'}>{user.role==='ADMIN'?'Use Create from Transcript to turn agreed decisions into saved projects and tasks.':'Projects will appear here when work is assigned to you.'}</Empty>)}
    {!loading&&!error&&data&&view==='detail'&&(data.project?<><section className="project-summary"><p className="client-name">{data.project.clientName}</p><p className="scope">{data.project.description}</p><dl><div><dt>Project manager</dt><dd>{data.project.managerName || data.project.managerId}</dd></div><div><dt>Delivery deadline</dt><dd>{date(data.project.deadline)}</dd></div></dl></section><div className="section-heading"><h2>{user.role==='AGENT'?'Your tasks':'Assigned tasks'}</h2><span>{data.tasks?.length || 0} tasks</span></div>{data.tasks?.length?<TaskList key={projectId} tasks={data.tasks}/>:<Empty title="No tasks to show">There are no assigned tasks available in this project.</Empty>}</>:<Empty title="Project unavailable">Return to projects to view work you can access.</Empty>)}
    {!loading&&!error&&data&&view==='tasks'&&(data.tasks?.length?<TaskList tasks={data.tasks} showProject openProject={id=>navigate('detail',id)}/>:<Empty title="No assigned tasks yet">Your assigned tasks will appear here with their scope, deadline and estimated hours.</Empty>)}
    {!loading&&!error&&data&&view==='team'&&<DirectoryList users={data.users || []}/>}
    {!loading&&error&&<button className="secondary" onClick={()=>setVersion(v=>v+1)}>Try again</button>}
    <footer className="workspace-footer">NovaWorks Technologies<span>Meeting to Execution</span></footer></main></div></>;
}
